### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by NicolasCARPi** [drupol/psrcas#4]
## Steps required to reproduce the problem

1. Read the README
2. Click the links in Configuration section

## Expected Result

* Get redirected to the documentation / code examples

## Actual Result

* 404 error

**Comment by drupol** [comment]
Thanks, the documentation can be found here:  https://psrcas.readthedocs.io 

I have to update the readme file.

**Comment by drupol** [comment]
Bonjour Nicolas,

It's fixed ;-)

Closing the issue.
